[package]
name = "discord_news"
version = "0.1.0"
authors = ["Anthony Huang <anthuang@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
